import assert from "node:assert";
import path from "node:path";
import { describe, it } from "node:test";
import { JIRA_CLIENT_CLOUD, XRAY_CLIENT_CLOUD } from "../../../test/clients.js";
import { getEnv } from "../../../test/util.js";
import { XraySource } from "./xray-source.js";

describe(path.relative(process.cwd(), import.meta.filename), () => {
  describe("xray cloud", () => {
    it("returns test plan data", async () => {
      const url = getEnv("jira-url");
      const source = new XraySource({
        jira: { client: JIRA_CLIENT_CLOUD, url: url },
        xray: { client: XRAY_CLIENT_CLOUD },
      });
      const testPlan = await source.getTestPlan("PAPA-152");
      assert.deepStrictEqual(testPlan, {
        id: "PAPA-152",
        name: "test plan with 150 tests",
        tests: [
          { id: "PAPA-151", name: "test 150", status: "pending", url: `${url}/browse/PAPA-151` },
          { id: "PAPA-150", name: "test 149", status: "pending", url: `${url}/browse/PAPA-150` },
          { id: "PAPA-149", name: "test 148", status: "pending", url: `${url}/browse/PAPA-149` },
          { id: "PAPA-148", name: "test 147", status: "pending", url: `${url}/browse/PAPA-148` },
          { id: "PAPA-147", name: "test 146", status: "pending", url: `${url}/browse/PAPA-147` },
          { id: "PAPA-146", name: "test 145", status: "pending", url: `${url}/browse/PAPA-146` },
          { id: "PAPA-145", name: "test 144", status: "pending", url: `${url}/browse/PAPA-145` },
          { id: "PAPA-144", name: "test 143", status: "pending", url: `${url}/browse/PAPA-144` },
          { id: "PAPA-143", name: "test 142", status: "pending", url: `${url}/browse/PAPA-143` },
          { id: "PAPA-142", name: "test 141", status: "pending", url: `${url}/browse/PAPA-142` },
          { id: "PAPA-141", name: "test 140", status: "pending", url: `${url}/browse/PAPA-141` },
          { id: "PAPA-140", name: "test 139", status: "pending", url: `${url}/browse/PAPA-140` },
          { id: "PAPA-139", name: "test 138", status: "pending", url: `${url}/browse/PAPA-139` },
          { id: "PAPA-138", name: "test 137", status: "pending", url: `${url}/browse/PAPA-138` },
          { id: "PAPA-137", name: "test 136", status: "pending", url: `${url}/browse/PAPA-137` },
          { id: "PAPA-136", name: "test 135", status: "pending", url: `${url}/browse/PAPA-136` },
          { id: "PAPA-135", name: "test 134", status: "pending", url: `${url}/browse/PAPA-135` },
          { id: "PAPA-134", name: "test 133", status: "pending", url: `${url}/browse/PAPA-134` },
          { id: "PAPA-133", name: "test 132", status: "pending", url: `${url}/browse/PAPA-133` },
          { id: "PAPA-132", name: "test 131", status: "pending", url: `${url}/browse/PAPA-132` },
          { id: "PAPA-131", name: "test 130", status: "pending", url: `${url}/browse/PAPA-131` },
          { id: "PAPA-130", name: "test 129", status: "pending", url: `${url}/browse/PAPA-130` },
          { id: "PAPA-129", name: "test 128", status: "pending", url: `${url}/browse/PAPA-129` },
          { id: "PAPA-128", name: "test 127", status: "pending", url: `${url}/browse/PAPA-128` },
          { id: "PAPA-127", name: "test 126", status: "pending", url: `${url}/browse/PAPA-127` },
          { id: "PAPA-126", name: "test 125", status: "pending", url: `${url}/browse/PAPA-126` },
          { id: "PAPA-125", name: "test 124", status: "pending", url: `${url}/browse/PAPA-125` },
          { id: "PAPA-124", name: "test 123", status: "pending", url: `${url}/browse/PAPA-124` },
          { id: "PAPA-123", name: "test 122", status: "pending", url: `${url}/browse/PAPA-123` },
          { id: "PAPA-122", name: "test 121", status: "pending", url: `${url}/browse/PAPA-122` },
          { id: "PAPA-121", name: "test 120", status: "pending", url: `${url}/browse/PAPA-121` },
          { id: "PAPA-120", name: "test 119", status: "pending", url: `${url}/browse/PAPA-120` },
          { id: "PAPA-119", name: "test 118", status: "pending", url: `${url}/browse/PAPA-119` },
          { id: "PAPA-118", name: "test 117", status: "pending", url: `${url}/browse/PAPA-118` },
          { id: "PAPA-117", name: "test 116", status: "pending", url: `${url}/browse/PAPA-117` },
          { id: "PAPA-116", name: "test 115", status: "pending", url: `${url}/browse/PAPA-116` },
          { id: "PAPA-115", name: "test 114", status: "pending", url: `${url}/browse/PAPA-115` },
          { id: "PAPA-114", name: "test 113", status: "pending", url: `${url}/browse/PAPA-114` },
          { id: "PAPA-113", name: "test 112", status: "pending", url: `${url}/browse/PAPA-113` },
          { id: "PAPA-112", name: "test 111", status: "pending", url: `${url}/browse/PAPA-112` },
          { id: "PAPA-111", name: "test 110", status: "pending", url: `${url}/browse/PAPA-111` },
          { id: "PAPA-110", name: "test 109", status: "pending", url: `${url}/browse/PAPA-110` },
          { id: "PAPA-109", name: "test 108", status: "pending", url: `${url}/browse/PAPA-109` },
          { id: "PAPA-108", name: "test 107", status: "pending", url: `${url}/browse/PAPA-108` },
          { id: "PAPA-107", name: "test 106", status: "pending", url: `${url}/browse/PAPA-107` },
          { id: "PAPA-106", name: "test 105", status: "pending", url: `${url}/browse/PAPA-106` },
          { id: "PAPA-105", name: "test 104", status: "pending", url: `${url}/browse/PAPA-105` },
          { id: "PAPA-104", name: "test 103", status: "pending", url: `${url}/browse/PAPA-104` },
          { id: "PAPA-103", name: "test 102", status: "pending", url: `${url}/browse/PAPA-103` },
          { id: "PAPA-102", name: "test 101", status: "pending", url: `${url}/browse/PAPA-102` },
          { id: "PAPA-101", name: "test 100", status: "pending", url: `${url}/browse/PAPA-101` },
          { id: "PAPA-100", name: "test 99", status: "pending", url: `${url}/browse/PAPA-100` },
          { id: "PAPA-99", name: "test 98", status: "pending", url: `${url}/browse/PAPA-99` },
          { id: "PAPA-98", name: "test 97", status: "pending", url: `${url}/browse/PAPA-98` },
          { id: "PAPA-97", name: "test 96", status: "pending", url: `${url}/browse/PAPA-97` },
          { id: "PAPA-96", name: "test 95", status: "pending", url: `${url}/browse/PAPA-96` },
          { id: "PAPA-95", name: "test 94", status: "pending", url: `${url}/browse/PAPA-95` },
          { id: "PAPA-94", name: "test 93", status: "pending", url: `${url}/browse/PAPA-94` },
          { id: "PAPA-93", name: "test 92", status: "pending", url: `${url}/browse/PAPA-93` },
          { id: "PAPA-92", name: "test 91", status: "pending", url: `${url}/browse/PAPA-92` },
          { id: "PAPA-91", name: "test 90", status: "pending", url: `${url}/browse/PAPA-91` },
          { id: "PAPA-90", name: "test 89", status: "pending", url: `${url}/browse/PAPA-90` },
          { id: "PAPA-89", name: "test 88", status: "pending", url: `${url}/browse/PAPA-89` },
          { id: "PAPA-88", name: "test 87", status: "pending", url: `${url}/browse/PAPA-88` },
          { id: "PAPA-87", name: "test 86", status: "pending", url: `${url}/browse/PAPA-87` },
          { id: "PAPA-86", name: "test 85", status: "pending", url: `${url}/browse/PAPA-86` },
          { id: "PAPA-85", name: "test 84", status: "pending", url: `${url}/browse/PAPA-85` },
          { id: "PAPA-84", name: "test 83", status: "pending", url: `${url}/browse/PAPA-84` },
          { id: "PAPA-83", name: "test 82", status: "pending", url: `${url}/browse/PAPA-83` },
          { id: "PAPA-82", name: "test 81", status: "pending", url: `${url}/browse/PAPA-82` },
          { id: "PAPA-81", name: "test 80", status: "pending", url: `${url}/browse/PAPA-81` },
          { id: "PAPA-80", name: "test 79", status: "pending", url: `${url}/browse/PAPA-80` },
          { id: "PAPA-79", name: "test 78", status: "pending", url: `${url}/browse/PAPA-79` },
          { id: "PAPA-78", name: "test 77", status: "pending", url: `${url}/browse/PAPA-78` },
          { id: "PAPA-77", name: "test 76", status: "pending", url: `${url}/browse/PAPA-77` },
          { id: "PAPA-76", name: "test 75", status: "pending", url: `${url}/browse/PAPA-76` },
          { id: "PAPA-75", name: "test 74", status: "pending", url: `${url}/browse/PAPA-75` },
          { id: "PAPA-74", name: "test 73", status: "pending", url: `${url}/browse/PAPA-74` },
          { id: "PAPA-73", name: "test 72", status: "pending", url: `${url}/browse/PAPA-73` },
          { id: "PAPA-72", name: "test 71", status: "pending", url: `${url}/browse/PAPA-72` },
          { id: "PAPA-71", name: "test 70", status: "pending", url: `${url}/browse/PAPA-71` },
          { id: "PAPA-70", name: "test 69", status: "pending", url: `${url}/browse/PAPA-70` },
          { id: "PAPA-69", name: "test 68", status: "pending", url: `${url}/browse/PAPA-69` },
          { id: "PAPA-68", name: "test 67", status: "pending", url: `${url}/browse/PAPA-68` },
          { id: "PAPA-67", name: "test 66", status: "pending", url: `${url}/browse/PAPA-67` },
          { id: "PAPA-66", name: "test 65", status: "pending", url: `${url}/browse/PAPA-66` },
          { id: "PAPA-65", name: "test 64", status: "pending", url: `${url}/browse/PAPA-65` },
          { id: "PAPA-64", name: "test 63", status: "pending", url: `${url}/browse/PAPA-64` },
          { id: "PAPA-63", name: "test 62", status: "pending", url: `${url}/browse/PAPA-63` },
          { id: "PAPA-62", name: "test 61", status: "pending", url: `${url}/browse/PAPA-62` },
          { id: "PAPA-61", name: "test 60", status: "pending", url: `${url}/browse/PAPA-61` },
          { id: "PAPA-60", name: "test 59", status: "pending", url: `${url}/browse/PAPA-60` },
          { id: "PAPA-59", name: "test 58", status: "pending", url: `${url}/browse/PAPA-59` },
          { id: "PAPA-58", name: "test 57", status: "pending", url: `${url}/browse/PAPA-58` },
          { id: "PAPA-57", name: "test 56", status: "pending", url: `${url}/browse/PAPA-57` },
          { id: "PAPA-56", name: "test 55", status: "pending", url: `${url}/browse/PAPA-56` },
          { id: "PAPA-55", name: "test 54", status: "pending", url: `${url}/browse/PAPA-55` },
          { id: "PAPA-54", name: "test 53", status: "pending", url: `${url}/browse/PAPA-54` },
          { id: "PAPA-53", name: "test 52", status: "pending", url: `${url}/browse/PAPA-53` },
          { id: "PAPA-52", name: "test 51", status: "pending", url: `${url}/browse/PAPA-52` },
          { id: "PAPA-51", name: "test 50", status: "pending", url: `${url}/browse/PAPA-51` },
          { id: "PAPA-50", name: "test 49", status: "pending", url: `${url}/browse/PAPA-50` },
          { id: "PAPA-49", name: "test 48", status: "pending", url: `${url}/browse/PAPA-49` },
          { id: "PAPA-48", name: "test 47", status: "pending", url: `${url}/browse/PAPA-48` },
          { id: "PAPA-47", name: "test 46", status: "pending", url: `${url}/browse/PAPA-47` },
          { id: "PAPA-46", name: "test 45", status: "pending", url: `${url}/browse/PAPA-46` },
          { id: "PAPA-45", name: "test 44", status: "pending", url: `${url}/browse/PAPA-45` },
          { id: "PAPA-44", name: "test 43", status: "pending", url: `${url}/browse/PAPA-44` },
          { id: "PAPA-43", name: "test 42", status: "pending", url: `${url}/browse/PAPA-43` },
          { id: "PAPA-42", name: "test 41", status: "pending", url: `${url}/browse/PAPA-42` },
          { id: "PAPA-41", name: "test 40", status: "pending", url: `${url}/browse/PAPA-41` },
          { id: "PAPA-40", name: "test 39", status: "pending", url: `${url}/browse/PAPA-40` },
          { id: "PAPA-39", name: "test 38", status: "pending", url: `${url}/browse/PAPA-39` },
          { id: "PAPA-38", name: "test 37", status: "pending", url: `${url}/browse/PAPA-38` },
          { id: "PAPA-37", name: "test 36", status: "pending", url: `${url}/browse/PAPA-37` },
          { id: "PAPA-36", name: "test 35", status: "pending", url: `${url}/browse/PAPA-36` },
          { id: "PAPA-35", name: "test 34", status: "pending", url: `${url}/browse/PAPA-35` },
          { id: "PAPA-34", name: "test 33", status: "pending", url: `${url}/browse/PAPA-34` },
          { id: "PAPA-33", name: "test 32", status: "pending", url: `${url}/browse/PAPA-33` },
          { id: "PAPA-32", name: "test 31", status: "pending", url: `${url}/browse/PAPA-32` },
          { id: "PAPA-31", name: "test 30", status: "pending", url: `${url}/browse/PAPA-31` },
          { id: "PAPA-30", name: "test 29", status: "pending", url: `${url}/browse/PAPA-30` },
          { id: "PAPA-29", name: "test 28", status: "pending", url: `${url}/browse/PAPA-29` },
          { id: "PAPA-28", name: "test 27", status: "pending", url: `${url}/browse/PAPA-28` },
          { id: "PAPA-27", name: "test 26", status: "pending", url: `${url}/browse/PAPA-27` },
          { id: "PAPA-26", name: "test 25", status: "pending", url: `${url}/browse/PAPA-26` },
          { id: "PAPA-25", name: "test 24", status: "pending", url: `${url}/browse/PAPA-25` },
          { id: "PAPA-24", name: "test 23", status: "pending", url: `${url}/browse/PAPA-24` },
          { id: "PAPA-23", name: "test 22", status: "pending", url: `${url}/browse/PAPA-23` },
          { id: "PAPA-22", name: "test 21", status: "pending", url: `${url}/browse/PAPA-22` },
          { id: "PAPA-21", name: "test 20", status: "pending", url: `${url}/browse/PAPA-21` },
          { id: "PAPA-20", name: "test 19", status: "pending", url: `${url}/browse/PAPA-20` },
          { id: "PAPA-19", name: "test 18", status: "pending", url: `${url}/browse/PAPA-19` },
          { id: "PAPA-18", name: "test 17", status: "pending", url: `${url}/browse/PAPA-18` },
          { id: "PAPA-17", name: "test 16", status: "pending", url: `${url}/browse/PAPA-17` },
          { id: "PAPA-16", name: "test 15", status: "pending", url: `${url}/browse/PAPA-16` },
          { id: "PAPA-15", name: "test 14", status: "pending", url: `${url}/browse/PAPA-15` },
          { id: "PAPA-14", name: "test 13", status: "pending", url: `${url}/browse/PAPA-14` },
          { id: "PAPA-13", name: "test 12", status: "pending", url: `${url}/browse/PAPA-13` },
          { id: "PAPA-12", name: "test 11", status: "pending", url: `${url}/browse/PAPA-12` },
          { id: "PAPA-11", name: "test 10", status: "pending", url: `${url}/browse/PAPA-11` },
          { id: "PAPA-10", name: "test 9", status: "pending", url: `${url}/browse/PAPA-10` },
          { id: "PAPA-9", name: "test 8", status: "pending", url: `${url}/browse/PAPA-9` },
          { id: "PAPA-8", name: "test 7", status: "pending", url: `${url}/browse/PAPA-8` },
          { id: "PAPA-7", name: "test 6", status: "pending", url: `${url}/browse/PAPA-7` },
          { id: "PAPA-6", name: "test 5", status: "pending", url: `${url}/browse/PAPA-6` },
          { id: "PAPA-5", name: "test 4", status: "pending", url: `${url}/browse/PAPA-5` },
          { id: "PAPA-4", name: "test 3", status: "pending", url: `${url}/browse/PAPA-4` },
          { id: "PAPA-3", name: "test 2", status: "pending", url: `${url}/browse/PAPA-3` },
          { id: "PAPA-2", name: "test 1", status: "pending", url: `${url}/browse/PAPA-2` },
        ],
        url: `${url}/browse/PAPA-152`,
      });
    });
  });
});
